CREATE USER 'klaver'@'localhost' IDENTIFIED BY 'HasanJasan123$';

GRANT USAGE ON * . * TO 'klaver'@'localhost' IDENTIFIED BY 'HasanJasan123$' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;

CREATE DATABASE IF NOT EXISTS `klaver` ;

GRANT ALL PRIVILEGES ON `klaver` . * TO 'klaver'@'localhost';